
name: push-main-checkout-prod
on:
  push:
    branches: [main]
    workflow-dispatch:
    tags:
      - "v*.*.*"
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod
      - run: ls
